version: '3.1'

services:
  api_test:
    image: postgres:15.1
    container_name: api_test
    restart: always
    environment:
      POSTGRES_DB: api_test
      POSTGRES_USER: mauro
      POSTGRES_PASSWORD: mauro12345
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
